##########################################
####### jekyll default vars
##########################################

title:            "PE BINARY CO., LTD."
email:            support@pebinary.com
description:      "A mobile research company based in Bangkok, Thailand."
markdown:         kramdown
#highlighter:      rouge
highlighter:      pygments
permalink:        pretty
source:           _source
destination:      _site
host:             localhost
port:             4000
#url:             http://pephumin.github.io
baseurl:          /pebinary.com
encoding:         utf-8
timezone:         Asia/Bangkok
exclude:          ['README.md', 'run', 'Gemfile', 'Gemfile.lock']
gems:             ['jekyll-sitemap']

##########################################
####### my custom vars
##########################################

domain:
  main-en:        http://www.pebinary.com
  main-th:        http://www.pebinary.co.th
  client:         http://www.binary.in.th
  member:         http://www.siamsquare.org
  support:        http://support.pebinary.com
