# Site settings

title: "PE BINARY CO., LTD."

email: support@pebinary.com

description: "A mobile research company based in Bangkok, Thailand."

#baseurl: "/pebinary.com"
baseurl: ""

#url: "http://www.pebinary.com"
#url: "https://pephumin.github.io"
url: "http://localhost:4000"

#twitter_username: pephumin
#github_username:  pephumin

encoding: utf-8
timezone: Asia/Bangkok

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'run', '_configlocal.yml']

# Build settings

markdown: kramdown
hilighter: pygments

gems: [github-pages, remote-include, sitemap_generator]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main-en"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blog-en"

