# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: PE Binary Co., Ltd.

email: support@pebinary.com

description: "A mobile research company based in Bangkok, Thailand."

baseurl: "/pebinary.com"

url: "http://www.pebinary.com"
# url: "https://pephumin.github.io"

# twitter_username: pephumin

# github_username:  pephumin

encoding: utf-8

timezone: Asia/Bangkok

# exclude: ['README.md']

# Build settings

markdown: kramdown

hilighter: pygments

#gems: [jekyll-assets, bourbon, neat]

#assets:
#  compress:
#    css: false | true | default - development: false, production: true
#    js: false | true | default - development: false, production: true
#  cache: false | directory | default: .asset-cache
#  cdn: https://cdn.example.com
#  skip_baseurl_with_cdn: false
#  skip_prefix_with_cdn: false
#  prefix: "/assets"
#  assets:
#    - "*.png"
#    - "bundle.css"
#  digest: true
#  sources:
#    - "_assets/folder"
