############################################################
#      ____  ______   ____  _____   _____    ______  __    #
#     / __ \/ ____/  / __ )/  _/ | / /   |  / __ \ \/ /    #
#    / /_/ / __/    / __  |/ //  |/ / /| | / /_/ /\  /     #
#   / ____/ /___   / /_/ // // /|  / ___ |/ _, _/ / /      #
#  /_/   /_____/  /_____/___/_/ |_/_/  |_/_/ |_| /_/       #
#                                                          #
############################################################


title:                "PE BINARY CO., LTD."
thaititle:            "บริษัท พีอี ไบนารี่ จำกัด"
email:                support@pebinary.com
description:          "A market research company specialised in mobile survey"
locale:               en
# permalink:            pretty
excerpt_separator:    <!--more-->
host:                 localhost
port:                 4000
# url:                  http://pephumin.github.io
# baseurl:              /pebinary.com
paginate:             5
paginate_path:        /blog/:num/
permalink:            /blog/:year/:month/:day/:title
quiet:                false
verbose:              true
encoding:             utf-8
timezone:             Asia/Bangkok
google_analytics:     UA-82554411-1

markdown:             kramdown
highlighter:          rouge
kramdown:
  input:              GFM
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  smart_quotes:       lsquo,rsquo,ldquo,rdquo
  hard_wrap:          false
  footnote_nr:        1
sass:
  sass_dir:           _sass
  style:              compressed

domains:
  main-en:            http://www.pebinary.com
  main-th:            http://www.pebinary.co.th
  support:            http://www.pebinary.net
  member:             http://www.siamsquare.org
  client:             http://www.siamsquare.org/admin

include:
  - _pages
  - API

exclude:
  - README.md
  - run
  - .DS_Store
  - Icon?
  - Gemfile
  - Gemfile.lock
  - database.rules.json
  - firebase.json
  - .firebaserc

gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-timeago

jekyll-archives:
  enabled:
    - categories
    - tags
  layout:             archive
  permalinks:
    category:         /blog/category/:name/
    tag:              /blog/tag/:name/
  limit:              5
  fullwidth:          false

compress_html:
  clippings:          []
  comments:           ["<!-- ", " -->"]
  endings:            []
  startings:          []
  blanklines:         true
  profile:            false

jekyll_timeago:
  depth:              1
  today:              "today"
  yesterday:          "yesterday"
  tomorrow:           "tomorrow"
  and:                "and"
  suffix:             "ago"
  prefix:             ""
  suffix_future:      ""
  prefix_future:      "in"
  years:              "years"
  year:               "year"
  months:             "months"
  month:              "month"
  weeks:              "weeks"
  week:               "week"
  days:               "days"
  day:                "day"

defaults:
  -
    scope:
      path:           ""
      type:           "posts"
      permalink:      /blog/:year/:month/:day/:title
    values:
      layout:         "blog"
      author:         "admin"
      author-email:   "admin@pebinary.com"
  -
    scope:
      path:           "_pages"
      type:           "pages"
    values:
      layout:         "main"
