##########################################
####### jekyll default vars
##########################################

title:                "PE BINARY CO., LTD."
email:                support@pebinary.com
description:          "A market research company specialised in mobile survey"
locale:               en-GB
markdown:             kramdown
highlighter:          rouge
#highlighter:         pygments
permalink:            pretty
excerpt_separator:    <!--more-->
host:                 localhost
port:                 4000
#url:                 http://pephumin.github.io
baseurl:              /pebinary.com
paginate:             5
paginate_path:        /blog/:num/
permalink:            /blog/:year/:month/:day/:title
encoding:             utf-8
timezone:             Asia/Bangkok
google_analytics:     yes
exclude:              ['README.md', 'run', '.DS_Store', 'Icon?', '_x']
gems:                 ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-timeago', 'jekyll-archives']

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /blog/category/:name/
    tag: /blog/tag/:name/

##########################################
####### my custom vars
##########################################

domain:
  main-en:            http://www.pebinary.com
  main-th:            http://www.pebinary.co.th
  client:             http://www.siamsquare.net
  member:             http://www.siamsquare.org
  support:            http://support.pebinary.com
