##########################################
####### jekyll default vars
##########################################

title:                "PE BINARY CO., LTD."
email:                support@pebinary.com
description:          "A market research company specialised in mobile survey"
markdown:             kramdown
highlighter:          rouge
#highlighter:         pygments
permalink:            pretty
excerpt_separator:    <!--more-->
host:                 localhost
port:                 4000
#url:                 http://pephumin.github.io
baseurl:              /pebinary.com
paginate:             5
paginate_path:        "/blog/:num/"
permalink:            /blog/:year/:month/:day/:title
encoding:             utf-8
timezone:             Asia/Bangkok
exclude:              ['README.md', 'run', '.DS_Store', 'Icon?', 'markdown.pl', '_u', '_plugin']
gems:                 ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-redirect-from', 'geo_pattern']


##########################################
####### my custom vars
##########################################

domain:
  main-en:            http://www.pebinary.com
  main-th:            http://www.pebinary.co.th
  client:             http://www.binary.in.th
  member:             http://www.siamsquare.org
  support:            http://support.pebinary.com
